#! /usr/bin/env bash

set -eux

# This script sets up fresh ubuntu 22.04+ installation
# to create a base image for our applications.

user=$user
password=$password

sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$user --gecos "User" $user

# set password
echo "$user:$password" | sudo chpasswd

echo User: $user has been created with password: $password
