#! /usr/bin/env bash

set -eux

# This script sets up fresh ubuntu 20.04+ installation
# to create a base image for our applications.

SCRIPTS_DIR="$(dirname "$(readlink -f "${0}")")"
# Needrestart and packer does not seem to work well together. Needrestart is
# propmpting for what services to restart and packer cannot answer, so it get stuck.
# This makes needrestart (l)ist the packages instead of prompting with a dialog.
# It also makes it only print kernel hints instead of prompting users to acknowledge.
# The alternative would be sudo apt-get remove -y needrestart.
#shellcheck disable=SC2016
echo -e '$nrconf{restart} = "l";\n$nrconf{kernelhints} = -1;' | sudo tee /etc/needrestart/needrestart.conf || true

user=$user
password=$password

sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$user --gecos "User" $user

# set password
echo "$user:$password" | sudo chpasswd

echo User: $user has been created with password: $password
