#! /usr/bin/env bash

set -eux

user=$user
password=$password

sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$user --gecos "User" $user

# set password
echo "$user:$password" | sudo chpasswd

echo User: $user has been created with password: $password
